extends:
  - eslint:all
  - airbnb

rules:
  react/jsx-filename-extension: 0
  no-param-reassign: 2
  import/no-extraneous-dependencies: ["error", {
    "webpack/**"
  }]
  arrow-parens: 0

parser: "babel-eslint"
parserOptions:
  sourceType: "module"
  allowImportExportEverywhere: true

