extends:
  - eslint:all
  - airbnb

rules:
  react/jsx-filename-extension: 0
  no-param-reassign: 2
  import/no-extraneous-dependencies: ["error", {
    "webpack/**"
  }]
  arrow-parens: 0
  comma-dangle: 0
  jsx-a11y/anchor-is-valid: ["error", {
    "components": [ "Link" ],
    "specialLink": [ "hrefLeft", "hrefRight" ],
    "aspects": [ "invalidHref", "preferButton" ]
  }]
  react/require-default-props: 0

parser: "babel-eslint"
parserOptions:
  sourceType: "module"
  allowImportExportEverywhere: true

